alias stn='subl -n'
alias emacs='/usr/local/Cellar/emacs/25.1/Emacs.app/Contents/MacOS/Emacs -nw'
alias git='$HOME/bin/git.sh'
alias file-roller='open -a betterzip'
alias runningvms='VBoxManage list runningvms'
alias tl='lpass-pw TeaLeavesVPN'
